---
Name: add_to_campaigns
After: "silverstripe/framework/#*"
---
SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - 'WebbuildersGroup\AddToCampaigns\Extensions\CampaignableGridField'
